//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_61e984(int64_t a1, int64_t a2, int64_t a3, uint32_t a4);
int64_t function_61e9c2(int64_t a1, int64_t a2, int64_t a3, int32_t a4, int64_t a5, int64_t a6, int64_t a7, int64_t a8, int64_t a9, int64_t a10, int64_t a11);
int64_t function_61eb58(int64_t a1);
int64_t function_61eb70(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7);
int64_t function_61ec2e(int64_t a1);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x61e950 - 0x61e984
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x61e950
    function_61ec2e(a3);
    int64_t v1; // 0x61e950
    int64_t v2; // 0x61e950
    int64_t v3; // 0x61e950
    int64_t result = function_61e9c2(a3, a1, a3, 0, v1, a2 + a1, a3, a4, v3, v2, (int64_t)&g1); // 0x61e96d
    return result;
}

// Address range: 0x61e984 - 0x61e9c2
int64_t function_61e984(int64_t a1, int64_t a2, int64_t a3, uint32_t a4) {
    // 0x61e984
    uint64_t v1; // 0x61e984
    int64_t v2 = v1 + a1; // 0x61e984
    int32_t v3 = a4; // 0x61e98d
    int64_t result = v2; // 0x61e98d
    int64_t v4 = a1; // 0x61e98d
    if (a4 > 5 == v1 < 0xfffffffffffffffd) {
        uint64_t v5 = (int64_t)(a4 - 4);
        result = v2 + 4;
        int64_t v6 = v5 + 0xfffffffc; // 0x61e99e
        *(int32_t *)a1 = *(int32_t *)v2;
        v4 = a1 + 4;
        int64_t v7 = result; // 0x61e9a7
        int64_t v8 = v4; // 0x61e9a7
        while (v5 >= 4) {
            // 0x61e998
            v5 = v6 & 0xffffffff;
            result = v7 + 4;
            v6 = v5 + 0xfffffffc;
            *(int32_t *)v8 = *(int32_t *)v7;
            v4 = v8 + 4;
            v7 = result;
            v8 = v4;
        }
        // 0x61e9a9
        v3 = (int32_t)v6 + 4;
        if (v3 == 0) {
            // 0x61e9c0
            return result;
        }
    }
    int32_t v9 = v3; // 0x61e9b5
    int64_t v10 = v4; // 0x61e984
    int64_t result2 = result + 1; // 0x61e9b0
    *(char *)v10 = *(char *)result;
    v9--;
    v10++;
    while (v9 != 0) {
        int64_t v11 = result2;
        result2 = v11 + 1;
        *(char *)v10 = *(char *)v11;
        v9--;
        v10++;
    }
    // 0x61e9c0
    return result2;
}

// Address range: 0x61e9c2 - 0x61ea90
int64_t function_61e9c2(int64_t a1, int64_t a2, int64_t a3, int32_t a4, int64_t a5, int64_t a6, int64_t a7, int64_t a8, int64_t a9, int64_t a10, int64_t a11) {
    // 0x61e9c2
    if ((char)a5 != 8) {
        // 0x61ea7f
        *(int32_t *)a9 = (int32_t)(a1 - a8);
        return a1 - a7;
    }
    int64_t v1 = a4; // 0x61e9c2
    int64_t v2 = a3;
    int64_t v3 = a2;
    int64_t v4 = a1;
    int64_t v5; // 0x61e9c2
    int64_t v6; // 0x61e9c2
    int64_t v7; // 0x61e9c2
    int64_t v8; // 0x61e9c2
    int32_t v9; // 0x61e9c2
    int32_t v10; // 0x61e9c2
    int64_t v11; // 0x61e9c2
    int64_t v12; // 0x61e9c2
    int64_t v13; // 0x61e9c2
    int64_t v14; // 0x61e9c2
    int64_t v15; // 0x61e9c2
    int64_t v16; // 0x61e9c2
    int64_t v17; // 0x61e9c2
    int64_t v18; // 0x61e9eb
    while (true) {
      lab_0x61e9d9:;
        int64_t v19 = v5;
        int64_t v20 = v1;
        int64_t v21 = v2;
        int64_t v22 = v8; // 0x61e9c2
        int64_t v23 = v3; // 0x61e9c2
        int64_t v24 = v4; // 0x61e9c2
        int64_t v25; // 0x61e9c2
        int32_t v26; // 0x61e9c2
        int64_t v27; // 0x61e9c2
        while (true) {
            // 0x61e9d9
            v4 = v24;
            int64_t v28 = v23;
            int64_t v29 = v21 & -256; // 0x61e9d9
            uint32_t v30 = (int32_t)v22; // 0x61e9db
            int32_t v31 = 2 * v30; // 0x61e9db
            char v32; // 0x61e9c2
            int64_t v33; // 0x61e9c2
            int32_t v34; // 0x61e9c2
            int64_t v35; // 0x61e9c2
            if (v31 != 0) {
                unsigned char v36 = *(char *)v28;
                int64_t v37 = v29 | (int64_t)v36;
                v35 = v37;
                v32 = v36;
                v34 = v31;
                v33 = v28;
                v27 = v37;
                v26 = v31;
                v25 = v28;
                if (v31 >= v30) {
                    // break -> 0x61e9eb
                    break;
                }
            } else {
                uint32_t v38 = *(int32_t *)v28; // 0x61e9df
                int64_t v39 = v28 + 4; // 0x61e9e1
                uint32_t v40 = 2 * v38; // 0x61e9e5
                int32_t v41 = v40 | (int32_t)(v28 < 0xfffffffffffffffc); // 0x61e9e5
                unsigned char v42 = *(char *)v39;
                int64_t v43 = v29 | (int64_t)v42;
                v35 = v43;
                v32 = v42;
                v34 = v41;
                v33 = v39;
                v27 = v43;
                v26 = v41;
                v25 = v39;
                if (!((v28 < 0xfffffffffffffffc ? v41 <= v38 : v40 < v38))) {
                    // break -> 0x61e9eb
                    break;
                }
            }
            // 0x61e9d1
            v21 = v35;
            *(char *)v4 = v32;
            v22 = v34;
            v23 = v33 + 1;
            v24 = v4 + 1;
        }
        // 0x61e9eb
        v18 = v20 + 1 & 0xffffffff;
        uint64_t v44 = v25;
        int64_t v45 = v27;
        int32_t v46 = 2 * v26; // 0x61e9fc
        bool v47 = v46 < v26; // 0x61e9fe
        int64_t v48 = v45; // 0x61e9fe
        int32_t v49 = v46; // 0x61e9fe
        int64_t v50 = v44; // 0x61e9fe
        uint32_t v51; // 0x61ea00
        uint32_t v52; // 0x61ea06
        if (v46 == 0) {
            // 0x61ea00
            v51 = *(int32_t *)v44;
            v50 = v44 + 4;
            v52 = 2 * v51;
            v49 = v52 | (int32_t)(v44 < 0xfffffffffffffffc);
            v47 = v44 < 0xfffffffffffffffc ? v49 <= v51 : v52 < v51;
            v48 = v45 & -256 | (int64_t)*(char *)v50;
        }
        int64_t v53 = v50;
        int32_t v54 = v49;
        int64_t v55 = v48;
        uint32_t v56 = (int32_t)(2 * v18 | (int64_t)false);
        while (!v47) {
            uint32_t v57 = v56 - 1; // 0x61e9f5
            uint32_t v58 = 2 * v57; // 0x61e9f5
            v44 = v53;
            v45 = v55;
            v46 = 2 * v54;
            v47 = v46 < v54;
            v48 = v45;
            v49 = v46;
            v50 = v44;
            if (v46 == 0) {
                // 0x61ea00
                v51 = *(int32_t *)v44;
                v50 = v44 + 4;
                v52 = 2 * v51;
                v49 = v52 | (int32_t)(v44 < 0xfffffffffffffffc);
                v47 = v44 < 0xfffffffffffffffc ? v49 <= v51 : v52 < v51;
                v48 = v45 & -256 | (int64_t)*(char *)v50;
            }
            // 0x61ea0a
            v53 = v50;
            v54 = v49;
            v55 = v48;
            v56 = (int32_t)(2 * (int64_t)v58 | (int64_t)(v58 < v57));
        }
        if (v56 < 3) {
            int32_t v59 = 2 * v54; // 0x61ea2e
            if (v59 != 0) {
                // 0x61ea3a
                v13 = v55;
                v9 = v59;
                v6 = v19;
                v16 = v53;
                v11 = v20;
                v14 = v55;
                v10 = v59;
                v7 = v19;
                v17 = v53;
                if (v59 < v54) {
                    goto lab_0x61ea64;
                } else {
                    goto lab_0x61ea3c;
                }
            } else {
                uint32_t v60 = *(int32_t *)v53; // 0x61ea32
                int64_t v61 = v53 + 4; // 0x61ea34
                uint32_t v62 = 2 * v60; // 0x61ea38
                int32_t v63 = v62 | (int32_t)(v53 < 0xfffffffffffffffc); // 0x61ea38
                v13 = v55;
                v9 = v63;
                v6 = v19;
                v16 = v61;
                v11 = v20;
                v14 = v55;
                v10 = v63;
                v7 = v19;
                v17 = v61;
                if (v53 < 0xfffffffffffffffc ? v63 <= v60 : v62 < v60) {
                    goto lab_0x61ea64;
                } else {
                    goto lab_0x61ea3c;
                }
            }
        } else {
            int64_t v64 = v55 % 256; // 0x61ea14
            int32_t v65 = 256 * v56 - 768 | (int32_t)v64; // 0x61ea17
            int64_t v66 = v53 + 1; // 0x61ea19
            v15 = v66;
            v12 = v4;
            if (v65 == -1) {
                // break -> 0x61ea7f
                break;
            }
            int32_t v67 = -1 - v65;
            int64_t v68 = v67 / 2; // 0x61ea27
            v13 = v64;
            v9 = v54;
            v6 = v68;
            v16 = v66;
            v11 = v20;
            v14 = v64;
            v10 = v54;
            v7 = v68;
            v17 = v66;
            if (v67 % 2 == 0) {
                goto lab_0x61ea3c;
            } else {
                goto lab_0x61ea64;
            }
        }
    }
    // 0x61ea7f
    *(int32_t *)a9 = (int32_t)(v12 - a8);
    return v15 - a7;
  lab_0x61ea3c:;
    int64_t v69 = v16;
    int64_t v70 = v6;
    uint32_t v71 = v9;
    int64_t v72 = v13;
    int32_t v73 = 2 * v71; // 0x61ea3e
    int32_t v74; // 0x61e9c2
    int64_t v75; // 0x61e9c2
    if (v73 != 0) {
        // 0x61ea4a
        v74 = v73;
        v75 = v69;
        v11 = v18;
        v14 = v72;
        v10 = v73;
        v7 = v70;
        v17 = v69;
        if (v73 < v71) {
            goto lab_0x61ea64;
        } else {
            goto lab_0x61ea4c;
        }
    } else {
        uint32_t v76 = *(int32_t *)v69; // 0x61ea42
        int64_t v77 = v69 + 4; // 0x61ea44
        uint32_t v78 = 2 * v76; // 0x61ea48
        int32_t v79 = v78 | (int32_t)(v69 < 0xfffffffffffffffc); // 0x61ea48
        v74 = v79;
        v75 = v77;
        v11 = v18;
        v14 = v72;
        v10 = v79;
        v7 = v70;
        v17 = v77;
        if (v69 < 0xfffffffffffffffc ? v79 <= v76 : v78 < v76) {
            goto lab_0x61ea64;
        } else {
            goto lab_0x61ea4c;
        }
    }
  lab_0x61ea64:;
    int64_t v80 = v14; // 0x61ea67
    int32_t v81 = v10; // 0x61ea67
    int64_t v82 = v7; // 0x61ea67
    int64_t v83 = v17; // 0x61ea67
    int64_t v84 = 2 * v11 & 0xfffffffe | 1; // 0x61ea67
    goto lab_0x61ea69;
  lab_0x61ea69:
    // 0x61ea69
    v3 = v83;
    v2 = v80;
    int64_t v85 = v84 + 2 + (int64_t)(v82 < 0xfffffffffffffb00); // 0x61ea70
    function_61e984(v4, v3, v2, (int32_t)v85);
    v1 = v85 & 0xffffffff;
    v8 = v81;
    v5 = v82;
    goto lab_0x61e9d9;
  lab_0x61ea4c:;
    uint64_t v86 = v75;
    int32_t v87 = 2 * v74; // 0x61ea51
    bool v88 = v87 < v74; // 0x61ea53
    int32_t v89 = v87; // 0x61ea53
    int64_t v90 = v86; // 0x61ea53
    uint32_t v91; // 0x61ea55
    uint32_t v92; // 0x61ea5b
    if (v87 == 0) {
        // 0x61ea55
        v91 = *(int32_t *)v86;
        v92 = 2 * v91;
        v89 = v92 | (int32_t)(v86 < 0xfffffffffffffffc);
        v88 = v86 < 0xfffffffffffffffc ? v89 <= v91 : v92 < v91;
        v90 = v86 + 4;
    }
    int64_t v93 = 2 * v18; // 0x61ea4f
    int64_t v94 = v90;
    int32_t v95 = v89;
    int64_t v96 = v93 & 0xfffffffe; // 0x61ea5d
    int32_t v97 = v95; // 0x61ea5d
    while (!v88) {
        // 0x61ea4c
        v86 = v94;
        v87 = 2 * v97;
        v88 = v87 < v97;
        v89 = v87;
        v90 = v86;
        if (v87 == 0) {
            // 0x61ea55
            v91 = *(int32_t *)v86;
            v92 = 2 * v91;
            v89 = v92 | (int32_t)(v86 < 0xfffffffffffffffc);
            v88 = v86 < 0xfffffffffffffffc ? v89 <= v91 : v92 < v91;
            v90 = v86 + 4;
        }
        // 0x61ea5d
        v93 = 2 * v96;
        v94 = v90;
        v95 = v89;
        v96 = v93 & 0xfffffffe;
        v97 = v95;
    }
    // 0x61ea5f
    v80 = v72;
    v81 = v95;
    v82 = v70;
    v83 = v94;
    v84 = v93 + 2 & 0xfffffffe;
    goto lab_0x61ea69;
}

// Address range: 0x61eb58 - 0x61eb70
int64_t function_61eb58(int64_t a1) {
    // 0x61eb58
    int64_t v1; // 0x61eb58
    int64_t v2; // 0x61eb58
    int64_t v3; // 0x61eb58
    __asm_syscall(2, a1, 14, v3, v2, v1);
    return __asm_syscall(127, a1, 14, v3, v2, v1);
}

// Address range: 0x61eb70 - 0x61ec2e
int64_t function_61eb70(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7) {
    int64_t v1 = __asm_syscall(a7, 0, a3, a4, a5, a6); // 0x61eb76
    int64_t v2 = v1; // 0x61eb7a
    if ((int32_t)v1 < 0) {
        v2 = function_61eb58(a7);
    }
    // 0x61eb7c
    bool v3; // 0x61eb70
    int64_t v4 = v3 ? -4 : 4; // 0x61eb84
    int64_t v5 = a7 + 15 + v4; // 0x61eb84
    int32_t * v6 = (int32_t *)v5; // 0x61eb8b
    int64_t v7 = v5 + v4; // 0x61eb8d
    uint32_t v8 = *(int32_t *)v7; // 0x61eb92
    int64_t v9 = v7 + v4; // 0x61eb92
    int64_t v10; // 0x61eb70
    int64_t v11 = v10 - 11; // 0x61eb99
    int64_t v12 = v11 - (int64_t)*(int32_t *)v11; // 0x61eba3
    int64_t v13 = v5 + (int64_t)*v6 - v12; // 0x61ebaa
    int64_t v14 = __asm_syscall(__asm_syscall(0, v13, 3, v12, 0xffffffff, 0), v9 + v4 + (int64_t)v8 - v12, 3, v12, v2 & 0xffffffff, 0); // 0x61ebe4
    int64_t v15 = v10 - v12 + v14 & -0x1000; // 0x61ebfa
    uint32_t v16 = *(int32_t *)v9; // 0x61ec16
    return __asm_syscall(v15, v13 + v14 - v15, 5, (int64_t)*v6, (int64_t)v16, 0);
}

// Address range: 0x61ec2e - 0x61ec34
int64_t function_61ec2e(int64_t a1) {
    // 0x61ec2e
    int64_t v1; // 0x61ec2e
    int64_t v2; // 0x61ec2e
    int64_t v3; // 0x61ec2e
    int64_t v4; // 0x61ec2e
    int64_t v5; // 0x61ec2e
    int64_t v6; // 0x61ec2e
    return function_61eb70(v3, v4, v5, v6, v2, v1, (int64_t)&g1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: upx (3.96)
// Detected functions: 6
